### ISSUE TITLE
Omelette du fromage

### ISSUE THREAD

**Issue by pmhoudry** [edoburu/django-parler#101]
*Omelette du fromage* is not a correct way to say *cheese omelet* in french. It means *cheese's omelet*. *Omelette au fromage* is the correct way.

**Comment by philippeowagner** [comment]
:+1:

**Comment by vdboor** [comment]
Hi! I know.. and maybe a bit overdue, but this is done on purpose. See: https://www.google.nl/search?q=%22omelette+du+fromage%22 :smile:

cc'ing the bugs: #17, #42, #59, #97

**Comment by pmhoudry** [comment]
I should have look for older bug reports. Thanks for your response.

**Comment by vdboor** [comment]
No problem. It's coming up every once in a while (you're the 5th), and while I like the practical joke, I also would like to hear from more French people what they think of it. Also, perhaps keeping this bug open would help others find it :wink:

**Comment by pmhoudry** [comment]
Yep. I think it works as a reference, but I doubt French people will get
it. In France, Dexter's lab is translated and distributed in French and
there may not be that much adults watching it in English.

http://www.dailymotion.com/video/x2a83eq_le-laboratoire-de-dexter-saison-1-episode-27-l-omelette-au-fromage_fun

You don't read French language everyday on Github and if you don't know the
Meme, it can be a little weird indeed. But it is not that critical.


2015-10-01 11:13 GMT+02:00 Diederik van der Boor <notifications@github.com>:

**Comment by vdboor** [comment]
Ah, thank you for clearing that up! That sheds some light on why some people didn't get it!
