### ISSUE TITLE
Feature: support language variant as django translation

### ISSUE THREAD

**Issue by tanyunshi** [edoburu/django-parler#106]
A language variant should be considered to be supported, even if it's not defined in the PARLER_LANGUAGES (just as what django does). 

For example,

In settings.py
```
PARLER_LANGUAGES = {
    None: (
        {'code': 'en',},
        {'code': 'fr',},
    ),
    'default': {
        'fallbacks': ['en'],          
        'hide_untranslated': False,   
    }
}
```
Then 
```
assert model.safe_translation_getter('title', language_code='fr') == 'bonjour'
assert model.safe_translation_getter('title', language_code='fr-ca') == 'bonjour'
assert model.safe_translation_getter('title', language_code='en') == 'hello'
```
Or 
```
with switch_language(model, 'fr-ca'):
    assert model.title == 'bonjour'
```

**Comment by tanyunshi** [comment]
Hi,  https://github.com/edoburu/django-parler/issues/98 might relates to this one.

**Comment by vdboor** [comment]
Good point, now I see what #98 could be about.
This needs some work across the whole app + unittests in place.
If someone can pick up that task and provide a PR, I'd be delighted!
Otherwise, you'll have to wait somewhat longer until I have time for it..

I'm in favor of using just `PARLER_LANGUAGES` to determine whether the language code should be rewritten before making the database query. When people want a `fr-ca` -> `fr` -> `en` fallback, it should be explicitly configured in the settings. Otherwise, when only `fr` and `en` are in `PARLER_LANGUAGES`, any variant will be rewritten.

**Comment by tanyunshi** [comment]
I will work on this but I need some help. :)

I am agree with you to use `PARLER_LANGUAGES` to determine whether or not to re-write the language to do the query. It seems to be clear.

However, I still have some doutes:
Today the ``PARLER_LANGUAGES`` doesnt restrict the translation language. For example, 
```
with switch_language(model, 'a-language-undefined'):
    model.title = 'some dirty strs'
    model.save()
assert model.safe_translation_getter('title', language_code='a-language-undefined) =='some dirty strs'
```

Therefore, we might have a problem: before we do the query, we dont know if the translation exists. For example, 
```
PARLER_LANGUAGES = {
    None: (
        {'code': 'en',},
        {'code': 'fr',},
    ),
}
```
Then,
```
model.set_current_language('fr-ca')
model.title = 'bonjour'
// here we have to query first with fr-ca, not fr
```

Otherwise, we can make the translation query with all possible variants and get the closed one. For example, we query the translation with language_code like ``fr-xx`` or ``fr`` if the given code is ``fr`` or ``fr-fr``. But it seems to complicate and be bad for the performance.

Another possible: we can restrict the translation with ``PARLER_LANGUAGES``: we can not translate a model in chinese if `cn` is not defined in ``PARLER_LANGUAGES``. To retrieve the translation, we also determine the language_code with `PARLER_LANGUAGES`. 

How do you think ?
