### ISSUE TITLE
get_absolute_url() return FieldError: Cannot resolve keyword u'slug' into field

### ISSUE THREAD

**Issue by shiriru** [edoburu/django-parler#108]
I have following model:
```Python
class Page(AbstractPage, TranslatableModel):
    ...
    translations = TranslatedFields(
        ...
        slug = models.SlugField(_("Slug"), max_length=200, null=True)
    )

    def get_absolute_url(self):
        return reverse('page:page-detail', kwargs={ 'slug' : self.slug })
```
And a detail view, going with it:
```Python
class PageDetailView(ViewUrlMixin, DetailView):
    model = Page
    template_name = 'page/page_detail.html'
    view_url_name = 'page:page-detail'
```

And url is:
```Python
urlpatterns = patterns('',
    ...
    url(r'^(?P<slug>[-\w]+)/$',
        PageDetailView.as_view(), name='page-detail'),
)
```
Now, this setup returns `FieldError: Cannot resolve keyword u'slug' into field`

How should I rewrite `get_absolute_url()` method to fetch proper translated slug?

**Comment by vdboor** [comment]
I'm quite surprised that the `slug` can't be resolved. Is there anything on your model that overrides/replaces it?

Note, when you use `i18n_patterns`, you may want to switch the Django language to render the proper URL:

```
def get_absolute_url(self):
    with switch_language(self):
        return reverse('page:page-detail', kwargs={ 'slug' : self.slug })
```

This however seems unrelated from your issue.

**Comment by macolo** [comment]
I've run into this error, however it was thrown by the view, not by calling `get_absolute_url`. You should probably use class-based views and mix in `TranslatableSlugMixin`.

**Comment by vdboor** [comment]
Yes, @macolo is correct here! I missed the fact you didn't use the `TranslatableSlugMixin`. The field indeed doesn't truely exist at the original model, that's why Django raises the error.
