### ISSUE TITLE
How to change language tabs url?

### ISSUE THREAD

**Issue by Emnalyeriar** [edoburu/django-parler#116]
Hey,
the server I am running my app on requires me to run my app with uwsgi on 127.0.0.1 on then admin sets up a proxy for that so the app is seen under some domain.
The problem with this is that the language tabs in translated models direct to link with 127.0.0.1 and not the domain it should.
Any tips on how to fix this?

**Comment by vdboor** [comment]
I wonder what other issues you'd run into with such unusual setup. However, I did remove the absolute URLs from `get_language_tabs()` in d3d699bc356e742152ae63b316a0534ec9e5c577. Those were unnecessary.

**Comment by Emnalyeriar** [comment]
It wasn't my decision to go this way, it's a setup that my client was using and I had to go with it.
Just downloaded version 1.6.1 and it works. Thanks for the help!
