### ISSUE TITLE
delete-translation URL broken?

### ISSUE THREAD

**Issue by maltebeckmann** [edoburu/django-parler#122]
Hi all,

When I try to delete a translation in the admin I get a 404. Turns out the URL:
/en/admin/events/event/2/change/delete-translation/en/
is wrong.
When I remove the "/change" from it, it works:
/en/admin/events/event/2/delete-translation/en/

Is this a bug?

I am running 
Django==1.9.2
django-parler==1.6.1
django-cms==3.2.1

**Comment by yakky** [comment]
Django 1.9 changed the path to the change form from ``/admin/app/model/id/`` to ``/admin/app/model/change/id/``
Probably the best option is to register both versions as catch all

**Comment by maltebeckmann** [comment]
Hi! Could you provide me with some pointers as to how I would do that?

**Comment by yakky** [comment]
@maltebeckmann I actually meant the option for parler to do this.
Declare a ``get_urls`` in your admin (like in https://github.com/edoburu/django-parler/blob/master/parler/admin.py#L308)
And add something like:

            return [
                url(r'^change/(.+)/delete-translation/(.+)/$',
                    self.admin_site.admin_view(self.delete_translation),
                    name='{0}_{1}_change_delete_translation'.format(*info)
                    ),
            ] + urlpatterns

**Comment by yakky** [comment]
@maltebeckmann see my PR above

**Comment by maltebeckmann** [comment]
@yakky Thanks - still getting my head around Django...
