### ISSUE TITLE
TranslatedFieldsModel.__unicode__() fails on objects with no configured language

### ISSUE THREAD

**Issue by mikek** [edoburu/django-parler#123]
It is possible that we have object translations in the database for currently disabled languages. [get_language_title()] (https://github.com/edoburu/django-parler/blob/828b341949572c68bd0adb38aa9f8c69dfc29ddd/parler/utils/i18n.py#L63) can not get language title for the translation if corresponding langauge it is not configured.
Would it be a proper workaround to represent object language by just it's language code in such a case?

**Comment by vdboor** [comment]
The PR is merged, and released as 1.6.2!
