### ISSUE TITLE
Compatibility issue django-parler with django-solo

### ISSUE THREAD

**Issue by sunjoomoon** [edoburu/django-parler#127]
Just wondered what I missing from using both django-parler and django-solo. Below is returned.
```
settings does not have a translation for the current language!
settings ID #1, language=en (tried fallbacks en)
Attempted to read attribute title.
```

If work standalone - just parler or just solo, it works fine. Seems somehow translated field is not available from the doc line number 495 https://github.com/edoburu/django-parler/blob/master/parler/models.py
```
        # None of the above, bail out!
        raise meta.model.DoesNotExist(
            "{0} does not have a translation for the current language!\n"
            "{0} ID #{1}, language={2}{3}".format(self._meta.verbose_name, self.pk, language_code, fallback_msg or ''
        ))
```
Any clue as to what I should look into? I use django 1.8.11

**Comment by yakky** [comment]
Could you provide the full traceback?
My gut feeling is this line https://github.com/lazybird/django-solo/blob/master/solo/models.py#L18 in django-solo confuses parler

**Comment by sunjoomoon** [comment]
Yes, further integration and work around returned below. 

- singleton simply not compatible, somehow random language is displayed. Does not produce any errors, just shows wrong language translations
- seems ORM gets confused, meta class ordering can not find the field. If fields ared in translated then they can not be found in almost all queries including meta class order
- compatibility issue is understandable, wish to find out the work around.

Hope to have these in FAQ section of the document and any work around as well, if at all. Maybe I am missing something.  Will do more testing in the coming days.

**Comment by sunjoomoon** [comment]
Figured out why.. it was because of cache by ```django-solo```. After disabling solo cache, all work fine. Sorry for the trouble.

**Comment by yakky** [comment]
@sunjoomoon thanks for sharing the solution

**Comment by sunjoomoon** [comment]
A little experience, one of those stupid things we often forget.  Even 3 seconds cache will significantly reduce DB hits, so I decided to go for 3 seconds, LoL.
