### ISSUE TITLE
mptt admin indent issue

### ISSUE THREAD

**Issue by sunjoomoon** [edoburu/django-parler#136]
Following http://django-parler.readthedocs.org/en/latest/advanced/mptt.html#integration-with-django-mptt, all seems okay but with below in admin.py

1) without ```list_display``` as below, title indent is okay. 
```
from django.contrib import admin
from parler.admin import TranslatableAdmin, TranslatableModelForm
from mptt.admin import MPTTModelAdmin
from mptt.forms import MPTTAdminForm
from .models import Category


class CategoryAdminForm(MPTTAdminForm, TranslatableModelForm):
    pass


class CategoryAdmin(TranslatableAdmin, MPTTModelAdmin):
    form = CategoryAdminForm

    def get_prepopulated_fields(self, request, obj=None):
        return {'slug': ('title',)}  # needed for translated fields


admin.site.register(Category, CategoryAdmin)
```

2) BUT if  ```list_display``` is used, then somehow second column value is indented. In this case, ```is_published``` is indented.
```
from django.contrib import admin
from parler.admin import TranslatableAdmin, TranslatableModelForm
from mptt.admin import MPTTModelAdmin
from mptt.forms import MPTTAdminForm
from .models import Category


class CategoryAdminForm(MPTTAdminForm, TranslatableModelForm):
    pass


class CategoryAdmin(TranslatableAdmin, MPTTModelAdmin):
    form = CategoryAdminForm
   ** list_display = ('title','is_published','order','language_column',)**

    def get_prepopulated_fields(self, request, obj=None):
        return {'slug': ('title',)}  # needed for translated fields


admin.site.register(Category, CategoryAdmin)
```

What am I missing?

**Comment by yakky** [comment]
@sunjoomoon what do you mean with "indented"? could you post a screenshot?

**Comment by sunjoomoon** [comment]
If I put below in admins.py, then mptt indent is applied to the is_published field instead of title field
```
    list_display = ('title','is_published','order','language_column',)
    list_editable = ('is_published','order')    
```
However, if I just pass all in admins.py, then it looks okay.
[
![mptt-indent-a](https://cloud.githubusercontent.com/assets/3462279/14758693/a70e58c2-0943-11e6-8742-ad1b260195c2.jpg)
![mptt-indent-b](https://cloud.githubusercontent.com/assets/3462279/14758694/a70f1fc8-0943-11e6-8d87-d1eaebc038a4.jpg)

](url)

**Comment by sunjoomoon** [comment]
Any tip? Is this a complex one? or just css or js thing? Any clue as to what to look into?

**Comment by sunjoomoon** [comment]
Further testing tells me this happens only with some fields ```BooleanField, IntegerField, CHOICES```

And css somehow is applied to the unwanted field.

**Comment by sunjoomoon** [comment]
Here we go, reminded me of importance of reading the doc again. 
https://django-mptt.github.io/django-mptt/admin.html#mptt-admin-mpttmodeladmin

```
class CategoryAdmin(TranslatableAdmin, MPTTModelAdmin):
    form = CategoryAdminForm
    mptt_indent_field = "title"         # replace this with your choice of indented field
    list_display = ('title','is_published','order','language_column',)

    def get_prepopulated_fields(self, request, obj=None):
        return {'slug': ('title',)}  # needed for translated fields


admin.site.register(Category, CategoryAdmin)   
```

**Comment by vdboor** [comment]
Thanks @sunjoomoon for clearing that up! Is this needed because our fields are translated, thus not standard model fields?

**Comment by sunjoomoon** [comment]
Not sure but in this case being explicit makes more sense. As I am unaware of what goes on under the surface, something to do with css class inserted in the unwanted field somehow.  Sorry for my ignorance..
