### ISSUE TITLE
Tricky issue with default language & other languages in admin inline

### ISSUE THREAD

**Issue by sunjoomoon** [edoburu/django-parler#137]
Using inline ```TranslatableTabularInline``` in the admin, things could be rather tricky..

For example, I have three languages ```en, ko, ja``` setup. In normal fields all fine but with inline things could go ticky.

1) users create 3 inlines, entered value in default language. Then, switching to ```ko``` and creating extra inlines (in addition to default 3 inlines), then saving is done without error. This causes empty field saved in the default language. Thus, next time accessing the record will produce below issue.

2) so wondered if there is any workaround - prevent creating extrainlines from non default languages or automatically prepopulate data to/from default and non default languages. 

```
DoesNotExist at /en/admin/appname/article/5/

More Content does not have a translation for the current language!
More Content ID #8, language=en (tried fallbacks en)
Attempted to read attribute title.
```

Further traceback returns below
in appname/models.py
```
        def __str__(self):

                        return "{0}".format(self.title)
```

and in  /parler/fields.py in __get__
```
            # Auto create is useless for __get__, will return empty titles everywhere.
            # Better use a fallback instead, just like gettext does.
            translation = None
            meta = self.field.meta
            try:
                            translation = instance._get_translated_model(use_fallback=True, meta=meta)     ...

            except meta.model.DoesNotExist as e:
                if self.field.any_language:
                    translation = instance._get_any_translated_model(meta=meta)  # returns None on error.
                if translation is None:
                    # Improve error message
```
and in parler/models.py in _get_translated_model
```
            raise meta.model.DoesNotExist(

                "{0} does not have a translation for the current language!\n"

                            "{0} ID #{1}, language={2}{3}".format(self._meta.verbose_name, self.pk, language_code, fallback_msg or ''

     ...

            ))
```

**Comment by vdboor** [comment]
I have a hard time understanding the bug.. could you provide an example project for it (or even better: a unit test that describes the problem?)

Note that you can use self.safe_translation_getter('title') in the `__unicode__()` method to make your objects more resilient against such translation issues.

**Comment by sunjoomoon** [comment]
Thanks. Let  me try that out. Learning parler a lot.
