### ISSUE TITLE
Inherit from model inheriting from TranslatableModel

### ISSUE THREAD

**Issue by georgema1982** [edoburu/django-parler#138]
I have a base class, let's call it A, that inherits from TranslatableModel with some translation fields. Now I have another class, say B, that inherits from A and needs to add more translation fields. I wonder if it's possible. From what I see, I will get "The model 'B' already has an associated translation field named 'translations'!" if I try to do that.

**Comment by jrief** [comment]
Have you tries to add to specify that field by hand?

```
class B(A):
    myfield = TranslatedField()

class BTranslation(TranslatedFieldsModel):
    master = models.ForeignKey(B, related_name='translations', null=True)
    myfield = models.CharField(max_length=50)

    class Meta:
        unique_together = [('language_code', 'master')]
```

**Comment by vdboor** [comment]
You can add a new translations block in model B, but it should have a different name then `translations`. That reverse-name is already taken by de ForeignKey of the main translation block.

**Comment by georgema1982** [comment]
@vdboor You are right. I did use a new translations block with a different name and it worked. But somehow it didn't work with treebeard. I believe it's treebeard's problem (treebeard doesn't work well with parler anyway) because mptt is happy with it.
