### ISSUE TITLE
Django Parler Admin is broken when template cache is enabled

### ISSUE THREAD

**Issue by Nekmo** [edoburu/django-parler#140]
when I try to access a page on Django Admin using Parler, I get a nice 500 error.

http://dpaste.com/1PXT6W0

The problem is here:
```
    def get_change_form_base_template(self):
        """
        Determine what the actual `change_form_template` should be.
        """
        opts = self.model._meta
        app_label = opts.app_label
        return _lazy_select_template_name((
            "admin/{0}/{1}/change_form.html".format(app_label, opts.object_name.lower()),
            "admin/{0}/change_form.html".format(app_label),
            "admin/change_form.html"
        ))

_lazy_select_template_name = lazy(select_template_name, six.text_type)
```

Lazy return a __proxy__ instance, and It isn't valid for Django Template Cache. When I replace this return to:

```
return "admin/change_form.html"
```

All works nice.

**Comment by vdboor** [comment]
Strange that I haven't seen this error before. This could be a Python 3 issue, as we declare the lazy function nicely with a `str` return value.

As workaround, you can create your own admin template, and define it as `change_form_template`. You'll have to include the language tabs manually (copy it from `admin/parler/change_form.html`)

**Comment by vstoykov** [comment]
@Nekmo is this raise the same error with Django 1.8? It can also be a regression in 1.9.

**Comment by Nekmo** [comment]
@vstoykov I don't know. I don't use Django 1.8.

**Comment by vstoykov** [comment]
@Nekmo Is it possible just to try run in with Django 1.8 to see if it will be broken or you are using 1.9 only features and will be unable to run it?

**Comment by vdboor** [comment]
You can try version 1.6.4 which should solve this issue!
