### ISSUE TITLE
Cannot resolve keyword 'title' into field issue

### ISSUE THREAD

**Issue by sunjoomoon** [edoburu/django-parler#141]
Using Q function, I do simple searching and without parler (single language, normal django model) all work fine. But with parler, 'title & summary' fields are not resolved. What should I look into?

Below is what I used in vews.py

```
    def get_queryset(self):
        result = super(ArticleListView, self).get_queryset()

        query = self.request.GET.get('q')

        if query:
            query_list = query.split()
            result = result.filter(
                reduce(operator.and_,
                       (Q(title__icontains=q) for q in query_list)) |
                reduce(operator.and_,
                       (Q(summary__icontains=q) for q in query_list))
            )
        return result 
```

**Comment by yakky** [comment]
@sunjoomoon when using normal queryset methods/operators the ``translations__field`` syntax must be used, to allow Django ORM to traverse the join

**Comment by vdboor** [comment]
@sunjoomoon @yakky , you can also use `MyModel.objects.translated(name="..", title="..")` which handles the `translations__` prefix on the fly for you.

Note that parler stores the translated fields in a separate table. We don't try to mask that fact as it would increase complexity. Instead, your application will have to deal with this fact when performing queries.

**Comment by sunjoomoon** [comment]
Thank you for the guide, learnt that now.  All multilanguage simple search works just great now.
