### ISSUE TITLE
Parler combined with Polymorphic and Django-1.7

### ISSUE THREAD

**Issue by jrief** [edoburu/django-parler#51]
Today I tried to upgrade to Django-1.7. Unfortunately this does not work, and I have no clue why. I then boiled my project down to a very simply Django installation and am still able to reproduce it.

My environment:
Django==1.7.1
django-parler==1.2.1
django-polymorphic==0.6
...and unimportant stuff...

in settings.py:
```
INSTALLED_APPS = (
    'polymorphic',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'parler',
    'my_demo',
)
```

Then I used the demo model.py from the docs:
```
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.encoding import python_2_unicode_compatible, force_text
from parler.models import TranslatableModel, TranslatedFields
from polymorphic import PolymorphicModel
from parler.managers import TranslatableManager

class Product(PolymorphicModel):
    code = models.CharField(blank=False, default='', max_length=16)
    price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)

@python_2_unicode_compatible
class Pen(TranslatableModel, Product):
    default_manager = TranslatableManager()

    translations = TranslatedFields(
        identifier=models.CharField(blank=False, default='', max_length=255)
    )

    def __str__(self):
        return force_text(self.identifier)
```

but I'am not able to even bootstrap this demo app:
```
   (... snip - bootstrapping ...)
  File ".../django/db/models/base.py", line 299, in add_to_class
    value.contribute_to_class(cls, name)
  File ".../parler/models.py", line 195, in contribute_to_class
    create_translations_model(cls, name, self.meta, **self.fields)
  File ".../parler/models.py", line 158, in create_translations_model
    translations_model = TranslatedFieldsModelBase(name, (TranslatedFieldsModel,), attrs)
  File ".../parler/models.py", line 677, in __new__
    new_class = super(TranslatedFieldsModelBase, mcs).__new__(mcs, name, bases, attrs)
  File ".../django/db/models/base.py", line 170, in __new__
    new_class.add_to_class(obj_name, obj)
  File ".../django/db/models/base.py", line 299, in add_to_class
    value.contribute_to_class(cls, name)
  File ".../django/db/models/fields/related.py", line 1585, in contribute_to_class
    super(ForeignObject, self).contribute_to_class(cls, name, virtual_only=virtual_only)
  File ".../django/db/models/fields/related.py", line 272, in contribute_to_class
    add_lazy_relation(cls, self, other, resolve_related_class)
  File ".../django/db/models/fields/related.py", line 84, in add_lazy_relation
    operation(field, model, cls)
  File ".../django/db/models/fields/related.py", line 271, in resolve_related_class
    field.do_related_class(model, cls)
  File ".../django/db/models/fields/related.py", line 307, in do_related_class
    self.set_attributes_from_rel()
  File ".../django/db/models/fields/related.py", line 304, in set_attributes_from_rel
    self.rel.set_field_name()
  File ".../django/db/models/fields/related.py", line 1256, in set_field_name
    self.field_name = self.field_name or self.to._meta.pk.name
AttributeError: 'NoneType' object has no attribute 'name'
```

BTW, the same happens if I use the ``Book`` example.

I saw that ``polymorphic/query.py`` attempts to handle something:

```
        # We might assume that self.model._meta.pk.name gives us the name of the primary key field,
        # but it doesn't. Therefore we use polymorphic_primary_key_name, which we set up in base.py.
```

but adding a breakpoint into that method is never triggered.

If you want, I can put a reference implementation on GitHub.

**Comment by jrief** [comment]
Just tested with Django-1.7.4, same result. Django-1.6.10 works fine.
Can someone please confirm or disprove that this combination does not work. 
Has this ever been tested? From what I see from the unit tests, this use case is not covered.

Unfortunately this is a show blocker to migrate my projects based on *parler* to Django-1.7.

**Comment by vdboor** [comment]
Hi!

You can combine both packages, I'm doing that for the django-fluent CMS code a lot.
The trick is combining the managers too. See the following example: http://django-parler.readthedocs.org/en/latest/advanced/polymorphicmodel.html#combining-managers

**Comment by jrief** [comment]
@vdboor 
this is exactly what I did, but this issue remains.

**Comment by jrief** [comment]
Thanks for reopening.
I'm still stucked to Django-1.6 because of this issue.

**Comment by jrief** [comment]
Now, my assumption is, that this is caused by a bug in Django itself. This conclusion comes from the experience that the unit tests with parler in combination with polymorphic work fine in Django<=1.6. They also work fine with Django>=1.7 and Python-3. But they fail with Django>=1.7 and Python-2.

It now would be great to create a small demo without any parler code, which demonstrates this problem, so that you (or I) can report a bug on the Django issue tracker. Can you please write such a demo or give me a hint how to write one?

**Comment by jrief** [comment]
A workaround to this problem, is to [construct the translations model manually](http://django-parler.readthedocs.org/en/latest/advanced/manual-models.html).

Please add this to the documentation, since until I discovered this alternative possibility, I was forced to stay with Django-1.6 longer than necessary. This issue then can be closed.

**Comment by vdboor** [comment]
Thanks for letting me know! did you manage to get an example app, or did you find this out in a different project? I'd love to try debugging the example app.

**Comment by jrief** [comment]
I found out through a hint on IRC. Additionally I had to move a ManyToMany relationship to an inheriting class. Only by applying both fixes, it solved the problem.

Have a look at PR #89 for details.

Anyway, thanks for this great project.
Will you be "Under the Hood"?

**Comment by vdboor** [comment]
Thanks for the update! I've merged most of the parts of #98 (through rebasing) and left the remaining commits in a custom branch (https://github.com/edoburu/django-parler/compare/jrief-test-polymorphic). This definitely needs more testing.

**Comment by jrief** [comment]
I think we can close this issue now since I never experienced it again.

**Comment by vdboor** [comment]
Thanks, that is a relief.
