### ISSUE TITLE
Integration with django-admin-sortable2

### ISSUE THREAD

**Issue by georgema1982** [edoburu/django-parler#57]
I'm using Admin sortable 2 in admin to order models by dragging them around. Parler works well with SortableAdminMixin but it doesn't work with SortableInlineAdminMixin. So basically, if the model is both translatable and inline, the two apps are not compatible. Just wonder if there's any tip or plan on integrating Admin sortable 2's SortableInlineAdminMixin.

**Comment by jrief** [comment]
@georgema1982 can this issue be closed now?

Simply add ``SortableInlineAdminMixin`` to your ``TranslatableTabularInline`` and override property template. Check both base templates for conflicting issues.

**Comment by georgema1982** [comment]
Ok, please close this. But I do hope there's a recipe on how to combine the two in the django-parler's document the same as how to combine parler with mptt

**Comment by vdboor** [comment]
Glad to know you worked it out!

I'd be happy to accept a pull request which adds such recipe to the documentation.
