### ISSUE TITLE
Rest Framework 3??

### ISSUE THREAD

**Issue by AdrianLC** [edoburu/django-parler#60]
Hi,

How's the integration with the new version of Rest Framework?
The docs mention a [TranslatableModelSerializer](http://django-parler.readthedocs.org/en/latest/advanced/rest-framework.html#example-code), but the `parler.contrib` package is empty...

The project seems really neat, but Rest Framework compatibility is a must for us.

Thanks!

**Comment by jrief** [comment]
I use django-parler together with django-restframework, but without the ``TranslatableModelSerializer ``. They work pretty well together. The current language is determined by the session, so you can even access the REST API without the language prefix in the URL.

**Comment by AdrianLC** [comment]
Thank you @jrief. The session doesn't really affect us much since we're talking about an internal API i.e. doesn't face users directly.

What we need mostly is serializing all the translations together, or a subset of languages so that we can send it to the cache in our frontend system. You think that would work easily?

**Comment by jrief** [comment]
Write your own serializer. Iterate over all languages and access the translated fields using the long notation, ie. ``translated__yourfieldname`` as explained in the parler docs.

**Comment by vdboor** [comment]
Hi!

The contents of `parler.contrib` moved to a separate package, https://github.com/edoburu/django-parler-rest This package is still based on rest framework v2, but a port to v3 is more then welcome!

**Comment by AdrianLC** [comment]
Hi @vdboor,

The update has been much easier that I would have thought. I have a fork [here](https://github.com/AdrianLC/django-parler-rest/tree/feature/DRF3) already in our project and everything seems to work so far. Would you please have a look, see if there is something wrong with parler's internals and such?

Also, how would you like to proceed with a merge? Do we want to maintain compatibility with Rest Framework 2, because that would make things much more complex. IMHO a note in the README indicating which version is compatible with 2 and 3 respectively could be enough.

**Comment by vdboor** [comment]
Wonderful to hear!
Yes, I'm all for releasing a new DRFv3 version only, and point users to the previous version for v2 compatibility. I guess most projects will move to v3 eventually too.

**Comment by vdboor** [comment]
FYI, the pull request is now merged into django-parler-rest. Once I've ported one of my projects to it, it can be released too.

**Comment by vdboor** [comment]
a DRF 3 version exists for some time now: https://github.com/edoburu/django-parler-rest/
