### ISSUE TITLE
Ambiguity in your documentation

### ISSUE THREAD

**Issue by ironhouzi** [edoburu/django-parler#62]
https://github.com/edoburu/django-parler/blob/master/docs/configuration.rst  

The section `PARLER_ENABLE_CACHING` (Line 110 I believe) states:  

> If needed, caching can be disabled. This is likely not needed.  

I find the latter sentence confusing. Are you stating that the configuration line `PARLER_ENABLE_CACHING = True` is probably not needed, or that it is likely that one doesn't want to disable caching?  

You might argue that my English comprehension is lacking, which I will not disagree. However, in my opinion documentation should be as unambiguous as possible and assuming that most people using your django app are non-native English speakers, you might want to communicate this point differently.

**Comment by vdboor** [comment]
Hi @ironhouzi, good thing to point out!

It's the latter indeed, that disabling the cache is something you rarely ever would do. It's good to have this flag though, so any issues with caching can be resolved by disabling it. Consider it a power-user setting, and most people shouldn't have to touch it.

**Comment by ironhouzi** [comment]
Thank you so much for clarifying this point. I have submitted a pull request #64 , so you can choose to merge that or do whatever you see fit.

**Comment by vdboor** [comment]
I've merged it! :)
