### ISSUE TITLE
Model instances created in interactive shell or data migrations have wrong default language.

### ISSUE THREAD

**Issue by mrmachine** [edoburu/django-parler#65]
My default language is `en-au` according to Django and Parler settings. But objects created from the interactive shell or a data migration have a default language of `en-us`.

This caused much confusion as I logged into the admin and clicked through to edit the object I had created in my data migration and found that all of its translated fields were empty in the form.

But in the change list, it showed me the `en-us` translation, causing even more confusion.

```python
>>> from django.conf import settings
>>> from django.contrib.auth import get_user_model
>>> from fluent_pages.models import PageLayout
>>> from fluent_pages.pagetypes.fluentpage.models import FluentPage
>>> from parler import appsettings

>>> User = get_user_model()

>>> settings.LANGUAGE_CODE
'en-au'

>>> appsettings.PARLER_DEFAULT_LANGUAGE_CODE
'en-au'

>>> admin = User.objects.get(username='admin')
>>> home = PageLayout.objects.get(key='home')

>>> page = FluentPage.objects.create(
    author=admin,
    title='Home Page',
    status='p',
    layout=home,
    override_url='/',
)

>>> page.get_current_language()
u'en-us'
```

**Comment by vdboor** [comment]
The Django management commands activate "en-us" by default. The settings are completely left alone. Django 1.8 also changes this behavior.

I dont think there is much we can do here, expect for adding a nice warning in the docs. I'd be really grateful if you can provide a nice PR for this.

**Comment by vstoykov** [comment]
@mrmachine when objects are created they depend on `django.utils.translation.get_language()` which is the current active language used from django i18n system.

Code executed not in the request/response cycle is not guaranteed to behave as you think if you do not use `translation.activate` or `translation.overwrite`.

As @vdboor said in Django 1.8 translation system is not activated in management commands and `translation.get_language()` will return `None`, which will make it impossible to save the object if you are not activated transaltion system with `translation.activate(settings.LANGUAGE_CODE)` or something you prefer.

I think that there is nothing that can be done from `django-parler` for now and issue need to be closed.

**Comment by vdboor** [comment]
Correct! Fact of dev-life is, that all projects had to adapt to using `translation.activate()` if they needed it.

**Comment by mrmachine** [comment]
@vdboor is it true now that with Django 1.8 we must call `activate(settings.LANGUAGE_CODE)` in every interactive shell or management command that queries a model with translatable fields?

**Comment by vdboor** [comment]
Sadly yes. Django changes this https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/#management-commands-and-locales While I'm not happy about the change, the rationale in https://code.djangoproject.com/ticket/24073 gives some hints why this was done.

You can also use `Model.objects.language(settings.LANGUAGE_CODE)` to query them.
