### ISSUE TITLE
Django 1.8 support?

### ISSUE THREAD

**Issue by anyong** [edoburu/django-parler#66]
I really want to use this package in my project, and I'm also hoping to use django 1.8 since this is a new project and 1.8 is the next LTS release due out in just a few days.

I get errors like this when trying to create a TranslatableModel in my app:

https://dpaste.de/oc54

Also, I noticed that the django.template.loader.find_template() function used in parler.template should be replaced with django.template.loader.get_template() for 1.8.

This will probably be where the problem is coming from:

https://docs.djangoproject.com/en/dev/ref/models/meta/#migrating-from-the-old-api

**Comment by sebleblanc** [comment]
FYI the snippet you pasted has expired. Can you repost it without an expiry time?

**Comment by vperron** [comment]
+1 to this, 1.8 support would be awesome.

**Comment by vperron** [comment]
There's more to it than just the template system, seems like the app&model loading also doesn't make Django 1.8 loader very happy.

**Comment by vdboor** [comment]
The latest github code has Django 1.8 support. Everything seems to work fine in the runserver, but tests still fail. If anyone could look into that, I'd be delighted!

**Comment by vdboor** [comment]
Correct that, code has been fixed to run in 1.8 too!

**Comment by vperron** [comment]
\o/

**Comment by anyong** [comment]
Thanks :D

**Comment by vdboor** [comment]
And.. 1.4 has just been uploaded to PyPI! :D
