### ISSUE TITLE
TranslatedField issues

### ISSUE THREAD

**Issue by cicuz** [edoburu/django-parler#67]
I think that on row 138 of file `forms.py` the last parameter is meant to be `**attrs[f_name].kwargs` instead of `**translated_fields[f_name].kwargs`.

~~Besides that, I'm having issues getting the field rendered: I'd like to use a CKEditor widget, and that does not seem to work, but even if I remove the custom widget setting the label is rendered as `%(contents)s:` instead of simply `contents`.~~

~~edit: the label thing was totally a (stupid) error on my side, but I still can't get the custom widget to work.~~

~~Is there any way I could fix this?~~

edit: well disregard all of that, I am a tool.

Thanks

**Comment by cicuz** [comment]
Issued a pull request to fix the wrong variable name;
I'd suggest merging it (or anyway fixing the small typo) as soon as possible, since it throws an exception immediately when building forms with custom widgets.

**Comment by vdboor** [comment]
I've merged #68 - can you confirm this is now correct? And if you can, please provide a unit test for this feature.
