### ISSUE TITLE
Manytomany fields in admin generate many queries

### ISSUE THREAD

**Issue by danialt** [edoburu/django-parler#70]
In admin when displaying Foreignkey fields with manytomany relationship, django runs a single query for each:

![change_clinic__english____django_suit](https://cloud.githubusercontent.com/assets/9436095/7183243/9f083f8e-e456-11e4-82cf-48485dd22078.png)

![change_clinic__english____django_suit](https://cloud.githubusercontent.com/assets/9436095/7183265/b6d49e78-e456-11e4-92a3-f146d5c11cdd.png)

So when there are 300 services there would be as many queries. Any hints?

**Comment by vdboor** [comment]
By default, parler caches the translations into the cache (e.g. memcached). So the next time, these fields no longer have to be requested. Make sure you have your `CACHES` set to point to memcached, e.g.:

```
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.memcached.MemcachedCache',
        'KEY_PREFIX': 'mysite.production',
        'LOCATION': '127.0.0.1:11211',
        'TIMEOUT': 24*3600
    },
}
```

In other situations, you can use `.prefetch_related('translations')` to prefetch all translations. Note that it will query all languages, not just your current language.

**Comment by danialt** [comment]
@vdboor Thank you for the input. I think the prefetch_related on get_queryset doesn't apply to `mantomany` filters/lists, correct me if I am wrong:

    def get_queryset(self, request):
        return super(ClinicAdmin, self).get_queryset(request).prefetch_related('translations', 'services__translations')

has no effect on number of queries. Adding caching on parler, though enabled, does not help since the same queries are not repeated but each item on those filters is called in a query for translated items (IDs are different each time). So, what I am looking for is a select_related/prefetch_related on inner filters. I will also review your apps meanwhile, in case you have solved such problem already.

**Comment by danialt** [comment]
In the hope of being useful for some others, here is how I solved the problem, reducing the queries from 2k to a handful in the admin:

    class MyModelAdminForm(TranslatableModelForm):
        class Meta:
            model = MyModel
            exclude = ()
    
        def __init__(self, *args, **kwargs):
            super(MyModelAdminForm, self).__init__(*args, **kwargs)
            self.fields['services'].queryset = Service.objects.prefetch_related('translations').all()
    
    class MyModelAdmin(TranslatableAdmin):
    
        form = MyModelAdminForm

So, override the form, and once inside, override the queryset with prefetch.

**Comment by vdboor** [comment]
Good solution, thanks for posting it!

I think the previous prefetch didn't work because of the note at https://docs.djangoproject.com/en/1.8/ref/models/querysets/#prefetch-related - when a queryset is filtered, it won't have prefetch information.

**Comment by pmartynov** [comment]
This solution works well for me. Thanks a lot.

**Comment by vdboor** [comment]
I've updated the docs so the performance tips are easier to find. I've also added an example for forms.
