### ISSUE TITLE
AttributeError when switching on caching

### ISSUE THREAD

**Issue by stefanw** [edoburu/django-parler#72]
I can't explain why this happened, but I switched on caching and got this on the first try. It worked afterwards.

```
...
 File ".../parler/models.py", line 418, in _get_translated_model
   object = get_cached_translation(self, language_code, related_name=meta.rel_name, use_fallback=use_fallback)
 File ".../parler/cache.py", line 71, in get_cached_translation
   values = _get_cached_values(instance, translated_model, language_code, use_fallback)
 File ".../parler/cache.py", line 119, in _get_cached_values
   if values.get('__FALLBACK__', False):
AttributeError: 'str' object has no attribute 'get'
```

It looks like `values` can be a non-empty string at some point(?) before properly initialized in the cache(?). Feel free to close this, as I could not repeat it.

**Comment by vdboor** [comment]
I've seen this happening when I switched cache backends, but it happened everywhere (not just parler specific). If you can do a "print" of this value, it will likely be a completely different cache entry.

**Comment by stefanw** [comment]
Sorry, could not repeat this. I would suggest putting another guard around this to check the type of `values` before using it as a dictionary.

**Comment by vdboor** [comment]
Well, given that it breaks everywhere, it doesn't seem to make much sense. Rather, users won't have to flush the cache anyways.
