### ISSUE TITLE
Caching completely broken in 1.4

### ISSUE THREAD

**Issue by skirsdeda** [edoburu/django-parler#73]
See this: https://github.com/edoburu/django-parler/commit/c450348a37477f98004f1191de0ae1d78fa34fa9#commitcomment-10963488

**Comment by skirsdeda** [comment]
Importing of DEFAULT_TIMEOUT is wrapped in try/except which always fails (goes to except), which in turn sets DEFAULT_TIMEOUT to 0 which effectively disables caching!

**Comment by vdboor** [comment]
Thanks for fixing this! The PR is merged
