### ISSUE TITLE
Deleting translation and incorrect breadcrumb

### ISSUE THREAD

**Issue by bashu** [edoburu/django-parler#76]
Deleting translation and broken breadcrumb, see screenshot
![screen shot 2015-05-01 at 14 06 37](https://cloud.githubusercontent.com/assets/144783/7428102/60efd2e4-f003-11e4-8e51-829c2edbb8d4.png)

Home -> /admin/fluent_pages/ ( should be /admin/ )
Fluentpage -> /admin/fluent_pages/page/ ( should be /admin/fluent_pages/ )
Pages -> /admin/fluent_pages/page/1/ ( should be   /admin/fluent_pages/page/)
Spanish: testa -> /admin/fluent_pages/1/delete-translation/ ( should be /admin/fluent_pages/page/1/ or /admin/fluent_pages/page/1/?language=es )

**Comment by vdboor** [comment]
Good catch!

I've been able to trace this to the templates of django-polymorphic-tree. It used the Django 1.3 constructs to build the breadcrumb, instead of using the `admin_urlname` filters. Fixed in edoburu/django-polymorphic-tree@52a0ad6e832f11fadbeffad3385f482ea7cf8b7b
