### ISSUE TITLE
_get_cached_values() looks for a deprecated 'fallback' key

### ISSUE THREAD

**Issue by mikek** [edoburu/django-parler#82]
KeyError: 'fallback' at parler/cache.py in _get_cached_values, line 126
Apparently, if we have something like `{'code': 'de', 'fallbacks': ['en', 'fr', 'it']},..` `_get_cached_values()` will fails under certain conditions.
Possibly introduced in 867241332cb8143307ca17630c918352e3eed99b

**Comment by vdboor** [comment]
PR got merged, closing ticket!
