### ISSUE TITLE
Indicate in the admin which fields are translatable

### ISSUE THREAD

**Issue by kvsn** [edoburu/django-parler#92]
Currently, there's no visual difference between translatable and untranslatable fields. We're using django-parler 1.4.

**Comment by jrief** [comment]
Did you add ``TranslatableAdmin`` to your ``admin.ModelAdmin`` class?
In the detail view, you then should see a tab, one for each language.

**Comment by kvsn** [comment]
Yes, I can see the tabs and the translations work fine. However, I currently get a full listing of all fields in each tab. Maybe I'm using it wrong? I think it would improve usability if you only show the translatable fields in the tabs, and move the rest to a separate section.

**Comment by jrief** [comment]
Please paste you model definition. If done correctly, you only see the translatable fields below the translatable tab.
Note one thing, the tab is on the top of the admin, but the translatable fields somewhere below. This can be confusing.

**Comment by kvsn** [comment]
Here's the model, as you can see only `description` is marked as translatable:
```
class Deal(TranslatableModel):
    name = models.CharField(max_length=64)
    logo = models.ImageField(upload_to='deals/logos/', storage=storage)
    background_image = models.ImageField(upload_to='deals/backgrounds/', storage=storage)
    expiration_date = models.DateField()
    link = models.URLField(help_text='Link to the landing page')
    position = models.IntegerField(help_text='Integer value indicating the position of the deal in the overview')
    is_visible = models.BooleanField(default=True)

    translations = TranslatedFields(
        description=models.CharField(max_length=255),
    )

    objects = DealManager()

    class Meta:
        ordering = ('position', 'id')

    def __repr__(self):
        return '<Deal: {name}>'.format(name=self.name)
```

Here's the admin, all fields occur on the tab:

![django-parler-admin](https://cloud.githubusercontent.com/assets/736178/8229875/202a3564-15bb-11e5-8dfe-ae9c61c16a1f.png)

**Comment by jrief** [comment]
A good practice is to group the fields in your modeladmin, say:

```
    fieldsets = (
        (None, {
            'fields': ('name', 'logo', 'background_image', ...),
        }),
        (_("Translatable Fields"), {
            'fields': ('description',)
        }),
```

 so that it becomes clear what is translatable and what not.

**Comment by kvsn** [comment]
That's certainly an improvement. It would be nice if the translatable fields were recognizable by default though, since the app is aware of them anyway. Also, I believe the translations of the inline `Benefit` descriptions cannot be added to a fieldset at the moment.

**Comment by vdboor** [comment]
I've been looking through the options, and I've made a fix for this!
If you'd use django-parler@bd1eea33f0e82b02dfd34946dcc657f417f4634d you'll have a CSS class `translatable-field` on both the input and label tag. You can also read `{{ field.is_translatable }}` in the template.

Other then that, my recommended approach would be using the fieldsets and `help_text` to make it evident which fields can be translated.

I've taken it more extreme in a few cases, to prevent users from editing non-translatable fields if they don't have the permissions for it. See  https://github.com/edoburu/django-fluent-pages/blob/master/fluent_pages/models/db.py#L115 and https://github.com/edoburu/django-fluent-pages/blob/master/fluent_pages/adminui/urlnodechildadmin.py#L168 for example.

**Comment by kvsn** [comment]
Thanks!

**Comment by shalltell** [comment]
I know this has been closed for a while, but for those who stumble upon this from a google search like I did, I did the following (thanks for the hint @vdboor):

```
class MyTranslatableAdmin(TranslatableAdmin):
    def get_exclude(self, request, obj=None):
        excluded_fields =  []
        if obj is not None and self.get_form_language(request) != settings.PARLER_DEFAULT_LANGUAGE_CODE:
            for field in self.model._meta.concrete_fields:
                if field.name not in obj._parler_meta.get_all_fields():
                    excluded_fields.append(field.name)

        return excluded_fields
```

This will exclude the fields completely for any language that isn't default.

**Comment by demoh2019** [comment]
> def get_exclude(self, request, obj=None):
>         excluded_fields =  []
>         if obj is not None and self.get_form_language(request) != settings.PARLER_DEFAULT_LANGUAGE_CODE:
>             for field in self.model._meta.concrete_fields:
>                 if field.name not in obj._parler_meta.get_all_fields():
>                     excluded_fields.append(field.name)
> 
>         return excluded_fields

Does not work with fields And does not delete Foreign Key fields

**Comment by shalltell** [comment]
@demoh2019 I ended up changing `self.model._meta.concrete_fields` to `self.model._meta.get_fields()` for my purposes.

**Comment by demoh2019** [comment]
> Я знаю, что это было закрыто некоторое время, но для тех, кто наткнется на это из поиска Google, как и я, я сделал следующее (спасибо за подсказку@vdboor):
> 
> ```
> class MyTranslatableAdmin(TranslatableAdmin):
>     def get_exclude(self, request, obj=None):
>         excluded_fields =  []
>         if obj is not None and self.get_form_language(request) != settings.PARLER_DEFAULT_LANGUAGE_CODE:
>             for field in self.model._meta.concrete_fields:
>                 if field.name not in obj._parler_meta.get_all_fields():
>                     excluded_fields.append(field.name)
> 
>         return excluded_fields
> ```
> 
> Это полностью исключит поля для любого языка, отличного от используемого по умолчанию.

`    def get_exclude(self, request, obj=None):
        excluded_fields =  []
        if obj is not None and self.get_form_language(request) != settings.PARLER_DEFAULT_LANGUAGE_CODE:
            for field in self.model._meta.get_fields():
                if field.name not in obj._parler_meta.get_all_fields():
                    excluded_fields.append(field.name)

        self.fields = ()
        return excluded_fields
`

**Comment by demoh2019** [comment]
> @demoh2019 I ended up changing `self.model._meta.concrete_fields` to `self.model._meta.get_fields()` for my purposes.

```
    def get_exclude(self, request, obj=None):
        excluded_fields =  []
        if obj is not None and self.get_form_language(request) != settings.PARLER_DEFAULT_LANGUAGE_CODE:
            for field in self.model._meta.get_fields():
                if field.name not in obj._parler_meta.get_all_fields():
                    excluded_fields.append(field.name)
        if excluded_fields:
            self.fields = ()
            self.exclude = ()
        return excluded_fields

```
Here is the final code that works
