### ISSUE TITLE
Doc translation mistake

### ISSUE THREAD

**Issue by omji** [edoburu/django-parler#97]
---> Easily translate “cheese omelet” into “omelette du fromage"

Not a major issue, but in french it rather translates to "omelette au fromage"

**Comment by vdboor** [comment]
You're not the first to mention this, and certainly not the last :grin:

See:
https://www.google.nl/search?q=%22omelette+du+fromage%22
http://django-parler.readthedocs.org/en/latest/background.html#package-naming

cc'ing the bugs:
https://github.com/edoburu/django-parler/issues/17
https://github.com/edoburu/django-parler/issues/42
https://github.com/edoburu/django-parler/issues/59
