### ISSUE TITLE
"Sublanguage"-fallback doesn't work as expected

### ISSUE THREAD

**Issue by melbic** [edoburu/django-parler#98]
In my current project the `LANGUAGE_CODE = 'de-ch' `. There are some translations e.g. de, fr, it, en .
As specified in  `parler.utils.i18n`  `de-ch` should fallback to `de`, but it doesn't. In the admin there is no default language selected, so the translated fields are empty, what is quite confusing.

**Comment by vdboor** [comment]
Could you post your `PARLER_LANGUAGES` setting, or provide an example (or even better a pull request)? I'm a bit confused how to reproduce or test this bug.

**Comment by tanyunshi** [comment]
This should already be fixed in 1.6.

**Comment by vdboor** [comment]
Thanks for letting us know @tanyunshi !
